chore: add ci test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,32 +1,28 @@
-name: Actions Runner Controller Demo
+name: ⚙️ K8s staging dispatch
+
 on:
+  repository_dispatch:
+    types: [dispatch]
   workflow_dispatch:
 
 jobs:
-  GoBuild:
+  deploy:
+    name: K8sDeploy
     runs-on: arc-runner-set
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.21.6
-      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
-      - name: Login to Aliyun Container Registry (ACR)
-        uses: aliyun/acr-login@v1
-        with:
-          login-server: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com
-          region-id: cn-shenzhen
-          username: "${{ secrets.REGISTRY_USERNAME }}"
-          password: "${{ secrets.REGISTRY_PASSWORD }}"
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Build and Push Docker Image
+      - name: TestFail
         run: |
-          go mod tidy
-          go build -o demo .
-          docker build -t demo:dev .
+          echo "TestFail"
+          exit 1
 
-  
+      - name: Warning
+        if: ${{ failure() }}
+        run: |
+          curl https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=663ca579-e4fb-4ded-83d1-63b8f944aa42 \
+            -H 'Content-Type: application/json' \
+            -d '{
+              "msgtype": "markdown",
+              "markdown": {
+                "content": "⚠️ K8s staging deploy failed, please check the logs.\n\n[Job Log]: https://github.com/dream-num/helm-chart-private/actions/runs/${{ github.run_id }}\n\n[Service]: ${{ github.event.client_payload.service }}"
+              }
+            }'
